#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "usage: $0 VERSION DIST_DIR" >&2
  exit 2
fi

version="$1"
dist_dir="$2"
repo="${HOMEBREW_TAP_REPOSITORY:-monksvaughan/homebrew-tap}"
branch="${HOMEBREW_TAP_BRANCH:-main}"
token="${HOMEBREW_TAP_GITHUB_TOKEN:-}"

if [[ -z "$token" ]]; then
  echo "HOMEBREW_TAP_GITHUB_TOKEN is required" >&2
  exit 1
fi

version_no_v="${version#v}"
formula_dir="$(mktemp -d)"
trap 'rm -rf "$formula_dir"' EXIT

git clone "https://x-access-token:${token}@github.com/${repo}.git" "$formula_dir"
cd "$formula_dir"
git checkout "$branch"
mkdir -p Formula
# Older releases used a Homebrew cask. Remove it so `brew install
# monksvaughan/tap/thin` resolves to the formula and avoids cask quarantine
# behaviour for this CLI binary.
rm -f Casks/thin.rb
rmdir Casks 2>/dev/null || true

checksum() {
  local archive="$1"
  awk -v archive="$archive" '$2 == archive { print $1 }' "${OLDPWD}/${dist_dir}/checksums.txt"
}

darwin_amd64="thin_${version_no_v}_darwin_amd64.tar.gz"
darwin_arm64="thin_${version_no_v}_darwin_arm64.tar.gz"
linux_amd64="thin_${version_no_v}_linux_amd64.tar.gz"
linux_arm64="thin_${version_no_v}_linux_arm64.tar.gz"

for archive in "$darwin_amd64" "$darwin_arm64" "$linux_amd64" "$linux_arm64"; do
  if [[ -z "$(checksum "$archive")" ]]; then
    echo "missing checksum for $archive in ${OLDPWD}/${dist_dir}/checksums.txt" >&2
    exit 1
  fi
done

cat > Formula/thin.rb <<EOF_FORMULA
# This file was generated by the thin release workflow. DO NOT EDIT.
class Thin < Formula
  desc "Low-latency HTTP proxy for reducing input-token usage in AI coding workflows"
  homepage "https://github.com/monksvaughan/thin"
  license "FSL-1.1-ALv2"
  version "${version_no_v}"

  on_macos do
    on_intel do
      url "https://github.com/monksvaughan/thin/releases/download/v#{version}/thin_#{version}_darwin_amd64.tar.gz"
      sha256 "$(checksum "$darwin_amd64")"
    end

    on_arm do
      url "https://github.com/monksvaughan/thin/releases/download/v#{version}/thin_#{version}_darwin_arm64.tar.gz"
      sha256 "$(checksum "$darwin_arm64")"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/monksvaughan/thin/releases/download/v#{version}/thin_#{version}_linux_amd64.tar.gz"
      sha256 "$(checksum "$linux_amd64")"
    end

    on_arm do
      url "https://github.com/monksvaughan/thin/releases/download/v#{version}/thin_#{version}_linux_arm64.tar.gz"
      sha256 "$(checksum "$linux_arm64")"
    end
  end

  def install
    bin.install "thin"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/thin version")
  end
end
EOF_FORMULA

git add -A

if git diff --cached --quiet; then
  echo "Homebrew formula already up to date"
  exit 0
fi

git status --short
git config user.name "thin release bot"
git config user.email "release-bot@users.noreply.github.com"
git commit -m "Update thin to ${version}"
git push origin "$branch"
